name: test_asset_variation
description: "Test - Asset Variation - flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  flutter_modular: ^6.3.2
  syncfusion_flutter_charts: ^24.2.6
  core_network:
    path: ../core_network
#  core_network:
#    git:
#      url: https://github.com/LordDeveloperJulio/core-network
#      path: core_network
#      branch: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true